apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apiresources.contrib.identityserver.io
spec:
  group: contrib.identityserver.io
  version: v1
  scope: Namespaced
  names:
    plural: apiresources
    singular: apiresource
    kind: ApiResource
    shortNames:
      - apr
      - apires
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ['spec']
      properties:
        spec:
          type: object
          properties:
            enabled:
              type: boolean
              description: Indicates if this resource is enabled. This defaults to true.
            name:
              type: string
              description: The unique name of the resource. If not set, the resource namespace and name (joined with a hyphen) are used instead.
            displayName:
              type: string
              description: Display name of the resource.
            description:
              type: string
              description: Description of the resource.
            userClaims:
              type: array
              description: List of accociated user claims that should be included when this resource is requested.
              items:
                type: string
            apiSecrets:
              type: array
              description: The API secret is used for the introspection endpoint. The API can authenticate with introspection using the API name and secret.
              items:
                type: object
                properties:
                  description:
                    type: string
                  value:
                    type: string
                    format: password
                  expiration:
                    format: date-time
                    type: string
                  type:
                    type: string
            scopes:
              type: array
              description: An API must have at least one scope. Each scope can have different settings.
              items:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                    description: Name of the scope. This is the value a client will use to request the scope.
                  displayName:
                    type: string
                    description:  This value will be used e.g. on the consent screen.
                  description:
                    type: string
                    description: This value will be used e.g. on the consent screen.
                  required:
                    type: boolean
                    description: Specifies whether the user can de-select the scope on the consent screen.
                  emphasize:
                    type: boolean
                    description: Specifies whether the consent screen will emphasize this scope. Use this setting for sensitive or important scopes.
                  showInDiscoveryDocument:
                    type: boolean
                    description: Specifies whether this scope is shown in the discovery document. This defaults to true.
                  userClaims:
                    type: array
                    description: List of user-claim types that should be included in the access token.
                    items:
                      type: string
