apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: identityapiresources.stable.contrib.identityserver.io
spec:
  group: stable.contrib.identityserver.io
  version: v1
  scope: Namespaced
  names:
    plural: identityapiresources
    singular: identityapiresource
    kind: IdentityApiResource
    shortNames:
    - idapi
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ['spec']
      properties:
        spec:
          type: object
          required:
          - name
          properties:
            apiSecrets:
              type: array
              items:
                type: object
                properties:
                  description:
                    type: string
                  value:
                    type: string
                    format: password
                  expiration:
                    format: date-time
                    type: string
                  type:
                    type: string
            scopes:
              type: array
              items:
                type: object
                required:
                - name
                properties:
                  name:
                    type: string
                  displayName:
                    type: string
                  description:
                    type: string
                  required:
                    type: boolean
                  emphasize:
                    type: boolean
                  showInDiscoveryDocument:
                    type: boolean
                  userClaims:
                    type: array
                    items:
                      type: string
            enabled:
              type: boolean
            name:
              type: string
            displayName:
              type: string
            description:
              type: string
            userClaims:
              type: array
              items:
                type: string
