apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: identityresources.contrib.identityserver.io
spec:
  group: contrib.identityserver.io
  version: v1
  scope: Namespaced
  names:
    plural: identityresources
    singular: identityresource
    kind: IdentityResource
    shortNames:
      - idr
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ['spec']
      properties:
        spec:
          type: object
          properties:
            enabled:
              type: boolean
              description: Indicates if this resource is enabled. This defaults to true.
            name:
              type: string
              description: The unique name of the resource. If not set, the resource namespace and name (joined with a hyphen) are used instead.
            displayName:
              type: string
              description: Display name of the resource.
            description:
              type: string
              description: Description of the resource.
            userClaims:
              type: array
              description: List of accociated user claims that should be included when this resource is requested.
              items:
                type: string
            required:
              type: boolean
              description: Specifies whether the user can de-select the scope on the consent screen (if the consent screen wants to implement such a feature).
            emphasize:
              type: boolean
              description: Specifies whether the consent screen will emphasize this scope (if the consent screen wants to implement such a feature). Use this setting for sensitive or important scopes.
            showInDiscoveryDocument:
              type: boolean
              description: Specifies whether this scope is shown in the discovery document. This defaults to true.
