apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: identityresources.contrib.identityserver.io
spec:
  group: contrib.identityserver.io
  version: v1
  scope: Namespaced
  names:
    plural: identityresources
    singular: identityresource
    kind: IdentityResource
    shortNames:
    - idr
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ['spec']
      properties:
        spec:
          type: object
          required:
          - name
          properties:
            required:
              type: boolean
            emphasize:
              type: boolean
            showInDiscoveryDocument:
              type: boolean
            enabled:
              type: boolean
            name:
              type: string
            displayName:
              type: string
            description:
              type: string
            userClaims:
              type: array
              items:
                type: string
