apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: oauthclients.stable.contrib.identityserver.io
spec:
  group: stable.contrib.identityserver.io
  version: v1
  scope: Namespaced
  names:
    plural: oauthclients
    singular: oauthclient
    kind: OauthClient
    shortNames:
    - idc
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ['spec']
      properties:
        spec:
          required:
            - clientId
            - clientName
            - allowedGrantTypes
          properties:
            enabled:
              type: boolean
            clientId:
              type: string
            clientSecrets:
              type: array
              items:
                properties:
                  value:
                    type: string
                    format: password
                  description:
                    type: string
                  expiration:
                    type: string
                    format: date-time
                  type:
                    type: string
                required:
                - value
            accessTokenType:
              type: string
              enum:
                - 'jwt'
                - 'reference'
            clientName:
              type: string
            clientUri:
              type: string
            logoUri:
              type: string
            requireConsent:
              type: boolean
            allowAccessTokensViaBrowser:
              type: boolean
            alwaysIncludeUserClaimsInIdToken:
              type: boolean
            allowedGrantTypes:
              type: array
              items:
                type: string
            redirectUris:
              type: array
              items:
                type: string
            frontChannelLogoutUri:
              type: string
            postLogoutRedirectUris:
              type: array
              items:
                type: string
            allowedScopes:
              type: array
              items:
                type: string
            updateAccessTokenClaimsOnRefresh:
              type: boolean
            allowedCorsOrigins:
              type: array
              items:
                type: string
            claims:
              type: array
              items:
                type: string
